os: linux
arch: amd64
dist: xenial

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

branches:
  only:
  - develop
  - master

before_install:
  - sudo apt-get update
  - sudo apt-get install -y "libhdf5-[[:digit:]]*"
  - sudo apt-get install -y libhdf5-dev

install:
  - echo $HDF5_DIR
  - echo $LIBRARY_DIRS
  - echo `dpkg -L libhdf5-dev`
  - python setup.py install

script:
  - pytest

env:
 global:
   - INCLUDE_DIRS=${PYTHON_INCLUDE}:/usr/local/include:/usr/include/hdf5/serial:/usr/include:/usr/lib/x86_64-linux-gnu/hdf5/serial/lib/include
   - LIBRARY_DIRS=${PYTHON_LIB}:/usr/local/lib:/usr/lib:/usr/lib/x86_64-linux-gnu/hdf5/serial:/usr/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/hdf5/serial/lib/lib
   - HDF5_DIR=/usr/lib/x86_64-linux-gnu/hdf5/serial:/usr/include/hdf5/serial:/usr/include:/usr/lib/x86_64-linux-gnu/hdf5/serial/lib/include:/usr/lib/x86_64-linux-gnu/hdf5/serial/lib/lib

jobs:
  allow_failures:
    - python: "3.4"
    - python: "3.5"
