os: linux
arch: amd64
dist: xenial

language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

branches:
  only:
  - develop
  - master

before_install:
  - sudo apt-get update
  - sudo apt-get install -y "libhdf5-[[:digit:]]*"

install:
  - python setup.py install

script:
  - pytest

env:
 global:
   - INCLUDE_DIRS=${PYTHON_INCLUDE}:/usr/local/include:/usr/include/hdf5/serial
   - LIBRARY_DIRS=${PYTHON_LIB}:/usr/local/lib:/usr/lib:/usr/lib/x86_64-linux-gnu/hdf5/serial

jobs:
  allow_failures:
    - python: "3.2"
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
